version: '3.8'
services:
  app:
    container_name: laravel
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=127.0.0.1'
    volumes:
      - .:/app
    ports:
      - "64520:8000"

  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_laravel_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "64521:80"

volumes:
  db_laravel_data:
