version: '3.8'
services:
  app:
    container_name: "${APP_NAME}-${APP_ENV}-laravel-app"
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "${CONTAINER_APP_PORT}:8000"

  db:
    image: mysql:8.0
    container_name: "${APP_NAME}-${APP_ENV}-database"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_laravel_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${APP_NAME}-${APP_ENV}-phpMyAdmin"
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "${CONTAINER_PMA_PORT}:80"

volumes:
  db_laravel_data:
